### ISSUE TITLE
Extension runs in background task

### ISSUE THREAD

**Issue by QuentiumYT** [darshanbhatta/RealTwit#1]
Hello, first of all, this is an interesting extension for twitter, thanks for that.

But after I installed the extension, it instantly get registered as a background app in chrome. I am wondering why such extension needs to monitor something outside of Twitter. Can you clarify the purpose of that feature? Thanks!

**Comment by darshanbhatta** [comment]
It’s used to lookup legacy verified users. That list is large so it would be wasteful to have it run on each Twitter tab.

It’s running as a service worker so as soon as it’s not being used, the background worker is inactive.

**Comment by QuentiumYT** [comment]
Oh so your extension uses the verified_users.json file with all users that are currently legacy users?
So this file won't change right?

**Comment by darshanbhatta** [comment]
Yup
